name: CI

on: [push, pull_request]

jobs:
  build_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: test
        env:
          CI: true
          COVERAGE: false
          FLAKEY: false
        run: |
          yarn install
          yarn test:bundle
